"""create order service schema

Revision ID: 0001
Revises:
Create Date: 2026-07-28 16:27:17.088672
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_inbox',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('consumer_name', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('payload_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'PROCESSED', 'FAILED', name='inbox_status_enum', native_enum=False, create_constraint=True, length=16), server_default='PROCESSING', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("payload_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_order_inbox_order_inbox_payload_hash_format')),
    sa.CheckConstraint('attempt_count >= 1', name=op.f('ck_order_inbox_order_inbox_attempt_count_positive')),
    sa.PrimaryKeyConstraint('event_id', 'consumer_name', name=op.f('pk_order_inbox'))
    )
    op.create_index('ix_order_inbox_status_received', 'order_inbox', ['status', 'received_at'], unique=False)
    op.create_table('order_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=32), server_default='ORDER', nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_version', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'PUBLISHED', 'FAILED', name='outbox_status_enum', native_enum=False, create_constraint=True, length=16), server_default='PENDING', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint("aggregate_type = 'ORDER'", name=op.f('ck_order_outbox_order_outbox_aggregate_type')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_order_outbox_order_outbox_attempt_count_non_negative')),
    sa.CheckConstraint('event_version >= 1', name=op.f('ck_order_outbox_order_outbox_event_version_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_outbox'))
    )
    op.create_index('ix_order_outbox_aggregate_created', 'order_outbox', ['aggregate_id', 'created_at'], unique=False)
    op.create_index('ix_order_outbox_status_next_created', 'order_outbox', ['status', 'next_attempt_at', 'created_at'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('cart_version', sa.BigInteger(), nullable=False),
    sa.Column('business_status', sa.Enum('PENDING_RESERVATION', 'RESERVED', 'CONFIRMED', 'REJECTED', 'CANCELLED', name='business_status_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('operation_state', sa.Enum('NONE', 'CANCELLATION_PENDING', 'REJECTION_PENDING', 'FAILED', name='operation_state_enum', native_enum=False, create_constraint=True, length=32), server_default='NONE', nullable=False),
    sa.Column('reservation_state', sa.Enum('REQUESTED', 'RESERVED', 'NOT_RESERVED', 'RELEASE_REQUESTED', 'RELEASED', 'UNKNOWN', name='reservation_state_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('target_terminal_status', sa.Enum('CANCELLED', 'REJECTED', name='target_terminal_status_enum', native_enum=False, create_constraint=True, length=16), nullable=True),
    sa.Column('rejection_reason_code', sa.String(length=64), nullable=True),
    sa.Column('rejection_reason_text', sa.String(length=500), nullable=True),
    sa.Column('cancellation_reason_code', sa.String(length=64), nullable=True),
    sa.Column('cancellation_reason_text', sa.String(length=500), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default='RUB', nullable=False),
    sa.Column('version', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('client_request_id', sa.UUID(), nullable=True),
    sa.Column('reservation_request_id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=True),
    sa.Column('release_request_id', sa.UUID(), nullable=True),
    sa.Column('reservation_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reservation_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reservation_attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reservation_last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('release_last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_phase', sa.Enum('RESERVATION', 'RELEASE', name='failure_phase_enum', native_enum=False, create_constraint=True, length=16), nullable=True),
    sa.Column('failure_reason_code', sa.String(length=64), nullable=True),
    sa.Column('failure_reason_text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(operation_state <> 'NONE') OR target_terminal_status IS NULL", name=op.f('ck_orders_orders_none_operation_has_no_target')),
    sa.CheckConstraint("\n            business_status <> 'REJECTED'\n            OR (operation_state = 'NONE' AND reservation_state IN ('NOT_RESERVED', 'RELEASED'))\n            ", name=op.f('ck_orders_orders_rejected_state')),
    sa.CheckConstraint("\n            operation_state NOT IN ('CANCELLATION_PENDING', 'REJECTION_PENDING')\n            OR (\n                reservation_state = 'RELEASE_REQUESTED'\n                AND release_request_id IS NOT NULL\n                AND (\n                    (operation_state = 'CANCELLATION_PENDING' AND target_terminal_status = 'CANCELLED')\n                    OR (operation_state = 'REJECTION_PENDING' AND target_terminal_status = 'REJECTED')\n                )\n            )\n            ", name=op.f('ck_orders_orders_pending_release_target')),
    sa.CheckConstraint("business_status <> 'CANCELLED' OR (operation_state = 'NONE' AND reservation_state = 'RELEASED')", name=op.f('ck_orders_orders_cancelled_state')),
    sa.CheckConstraint("business_status <> 'CONFIRMED' OR (operation_state = 'NONE' AND reservation_state = 'RESERVED')", name=op.f('ck_orders_orders_confirmed_state')),
    sa.CheckConstraint("currency = 'RUB'", name=op.f('ck_orders_orders_currency_rub')),
    sa.CheckConstraint("operation_state <> 'FAILED' OR (failure_phase IS NOT NULL AND failure_reason_code IS NOT NULL)", name=op.f('ck_orders_orders_failed_has_reason')),
    sa.CheckConstraint('\n            (release_requested_at IS NULL AND release_deadline_at IS NULL)\n            OR (\n                release_requested_at IS NOT NULL\n                AND release_deadline_at > release_requested_at\n                AND release_attempt_count >= 1\n            )\n            ', name=op.f('ck_orders_orders_release_deadline_pair')),
    sa.CheckConstraint('\n            (reservation_requested_at IS NULL AND reservation_deadline_at IS NULL)\n            OR (\n                reservation_requested_at IS NOT NULL\n                AND reservation_deadline_at > reservation_requested_at\n                AND reservation_attempt_count >= 1\n            )\n            ', name=op.f('ck_orders_orders_reservation_deadline_pair')),
    sa.CheckConstraint('cart_version > 0', name=op.f('ck_orders_orders_cart_version_positive')),
    sa.CheckConstraint('customer_id > 0', name=op.f('ck_orders_orders_customer_id_positive')),
    sa.CheckConstraint('release_attempt_count >= 0', name=op.f('ck_orders_orders_release_attempt_count_non_negative')),
    sa.CheckConstraint('reservation_attempt_count >= 0', name=op.f('ck_orders_orders_reservation_attempt_count_non_negative')),
    sa.CheckConstraint('supplier_id > 0', name=op.f('ck_orders_orders_supplier_id_positive')),
    sa.CheckConstraint('total_amount > 0', name=op.f('ck_orders_orders_total_amount_positive')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_orders_orders_version_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('customer_id', 'cart_version', name='uq_orders_customer_cart_version'),
    sa.UniqueConstraint('reservation_request_id', name='uq_orders_reservation_request_id')
    )
    op.create_index('ix_orders_business_operation_created', 'orders', ['business_status', 'operation_state', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_orders_customer_created_id', 'orders', ['customer_id', sa.text('created_at DESC'), sa.text('id DESC')], unique=False)
    op.create_index('ix_orders_release_deadline_pending', 'orders', ['release_deadline_at'], unique=False, postgresql_where=sa.text("operation_state IN ('CANCELLATION_PENDING', 'REJECTION_PENDING', 'FAILED') AND release_deadline_at IS NOT NULL"))
    op.create_index('ix_orders_reservation_deadline_pending', 'orders', ['reservation_deadline_at'], unique=False, postgresql_where=sa.text("business_status = 'PENDING_RESERVATION' AND reservation_state IN ('REQUESTED', 'UNKNOWN')"))
    op.create_index('ix_orders_supplier_created_id', 'orders', ['supplier_id', sa.text('created_at DESC'), sa.text('id DESC')], unique=False)
    op.create_index('uq_orders_release_request_id', 'orders', ['release_request_id'], unique=True, postgresql_where=sa.text('release_request_id IS NOT NULL'))
    op.create_table('order_idempotency',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('operation_type', sa.String(length=32), server_default='CREATE_ORDER', nullable=False),
    sa.Column('key_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('request_fingerprint', sa.CHAR(length=64), nullable=False),
    sa.Column('state', sa.Enum('IN_PROGRESS', 'COMPLETED', 'FAILED_RETRYABLE', name='idempotency_state_enum', native_enum=False, create_constraint=True, length=32), server_default='IN_PROGRESS', nullable=False),
    sa.Column('owner_token', sa.UUID(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('response_status', sa.SmallInteger(), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("key_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_order_idempotency_order_idempotency_key_hash_format')),
    sa.CheckConstraint("operation_type = 'CREATE_ORDER'", name=op.f('ck_order_idempotency_order_idempotency_operation_type')),
    sa.CheckConstraint("request_fingerprint ~ '^[0-9a-f]{64}$'", name=op.f('ck_order_idempotency_order_idempotency_fingerprint_format')),
    sa.CheckConstraint('customer_id > 0', name=op.f('ck_order_idempotency_order_idempotency_customer_id_positive')),
    sa.CheckConstraint('response_status IS NULL OR response_status BETWEEN 100 AND 599', name=op.f('ck_order_idempotency_order_idempotency_response_status_range')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_idempotency_order_id_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_idempotency')),
    sa.UniqueConstraint('customer_id', 'operation_type', 'key_hash', name='uq_order_idempotency_customer_operation_key')
    )
    op.create_index('ix_order_idempotency_expires_at', 'order_idempotency', ['expires_at'], unique=False)
    op.create_index('ix_order_idempotency_state_lease', 'order_idempotency', ['state', 'lease_expires_at'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('product_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('supplier_id_snapshot', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("currency = 'RUB'", name=op.f('ck_order_items_order_items_currency_rub')),
    sa.CheckConstraint('line_total >= 0', name=op.f('ck_order_items_order_items_line_total_non_negative')),
    sa.CheckConstraint('product_id > 0', name=op.f('ck_order_items_order_items_product_id_positive')),
    sa.CheckConstraint("btrim(product_name_snapshot) <> ''", name=op.f('ck_order_items_order_items_product_name_non_blank')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_order_items_quantity_positive')),
    sa.CheckConstraint('supplier_id_snapshot > 0', name=op.f('ck_order_items_order_items_supplier_id_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_order_items_order_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items')),
    sa.UniqueConstraint('order_id', 'product_id', name='uq_order_items_order_product')
    )
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('business_status_before', sa.Enum('PENDING_RESERVATION', 'RESERVED', 'CONFIRMED', 'REJECTED', 'CANCELLED', name='history_business_status_before_enum', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('business_status_after', sa.Enum('PENDING_RESERVATION', 'RESERVED', 'CONFIRMED', 'REJECTED', 'CANCELLED', name='history_business_status_after_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('operation_state_before', sa.Enum('NONE', 'CANCELLATION_PENDING', 'REJECTION_PENDING', 'FAILED', name='history_operation_state_before_enum', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('operation_state_after', sa.Enum('NONE', 'CANCELLATION_PENDING', 'REJECTION_PENDING', 'FAILED', name='history_operation_state_after_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reservation_state_before', sa.Enum('REQUESTED', 'RESERVED', 'NOT_RESERVED', 'RELEASE_REQUESTED', 'RELEASED', 'UNKNOWN', name='history_reservation_state_before_enum', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('reservation_state_after', sa.Enum('REQUESTED', 'RESERVED', 'NOT_RESERVED', 'RELEASE_REQUESTED', 'RELEASED', 'UNKNOWN', name='history_reservation_state_after_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.Enum('CUSTOMER', 'SUPPLIER', 'SYSTEM', 'KAFKA_CONSUMER', name='actor_type_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('version_before', sa.BigInteger(), nullable=False),
    sa.Column('version_after', sa.BigInteger(), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('reason_text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actor_id IS NULL OR actor_id > 0', name=op.f('ck_order_status_history_order_status_history_actor_id_positive')),
    sa.CheckConstraint("\n            (\n                version_before = 0\n                AND business_status_before IS NULL\n                AND operation_state_before IS NULL\n                AND reservation_state_before IS NULL\n            )\n            OR (\n                version_before >= 1\n                AND business_status_before IS NOT NULL\n                AND operation_state_before IS NOT NULL\n                AND reservation_state_before IS NOT NULL\n            )\n            ", name=op.f('ck_order_status_history_order_status_history_before_state_consistency')),
    sa.CheckConstraint('version_after > version_before', name=op.f('ck_order_status_history_order_status_history_version_increases')),
    sa.CheckConstraint('version_after >= 1', name=op.f('ck_order_status_history_order_status_history_version_after_positive')),
    sa.CheckConstraint('version_before >= 0', name=op.f('ck_order_status_history_order_status_history_version_before_non_negative')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_status_history_order_id_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_status_history')),
    sa.UniqueConstraint('order_id', 'version_after', name='uq_order_status_history_order_version')
    )
    op.create_index('ix_order_status_history_order_created_id', 'order_status_history', ['order_id', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_status_history_order_created_id', table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_order_idempotency_state_lease', table_name='order_idempotency')
    op.drop_index('ix_order_idempotency_expires_at', table_name='order_idempotency')
    op.drop_table('order_idempotency')
    op.drop_index('uq_orders_release_request_id', table_name='orders', postgresql_where=sa.text('release_request_id IS NOT NULL'))
    op.drop_index('ix_orders_supplier_created_id', table_name='orders')
    op.drop_index('ix_orders_reservation_deadline_pending', table_name='orders', postgresql_where=sa.text("business_status = 'PENDING_RESERVATION' AND reservation_state IN ('REQUESTED', 'UNKNOWN')"))
    op.drop_index('ix_orders_release_deadline_pending', table_name='orders', postgresql_where=sa.text("operation_state IN ('CANCELLATION_PENDING', 'REJECTION_PENDING', 'FAILED') AND release_deadline_at IS NOT NULL"))
    op.drop_index('ix_orders_customer_created_id', table_name='orders')
    op.drop_index('ix_orders_business_operation_created', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_order_outbox_status_next_created', table_name='order_outbox')
    op.drop_index('ix_order_outbox_aggregate_created', table_name='order_outbox')
    op.drop_table('order_outbox')
    op.drop_index('ix_order_inbox_status_received', table_name='order_inbox')
    op.drop_table('order_inbox')
    # ### end Alembic commands ###
