FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt requirements-dev.txt ./
RUN pip install --no-cache-dir -r requirements-dev.txt
COPY pytest.ini .
COPY app ./app
COPY tests ./tests
CMD ["pytest", "-q"]
